---
title: "Formula 1 2022 Regulation Changes"
subtitle: "How did the 2022 F1 Regulations change the sport for better and for worse"
author: 
  - Michael Fang
thanks: "Code and data are available at: https://github.com/fanger2791/F1_Regulations."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

# Introduction



# Data

# Results

```{r}
#| echo: false
#| warning: false
#| message: false

library(ggplot2)
library(readr)
library(dplyr)

ver_jeddah_2022 <- read_csv("../data/analysis_data/verstappen_laps_jeddah_2022_cleaned.csv")
ver_jeddah_2021 <- read_csv("../data/analysis_data/verstappen_laps_jeddah_2021_cleaned.csv")

# Add a season column to each dataframe
ver_jeddah_2021$Season <- '2021'
ver_jeddah_2022$Season <- '2022'

# Combine the two dataframes
combined_df <- rbind(ver_jeddah_2021, ver_jeddah_2022)

# Create the plot
ggplot(combined_df, aes(x = `Lap #`, y = `LapTime in Seconds`, color = Season)) +
  geom_line() + # This will connect points with lines, showing the trend
  geom_point() + # This will plot individual lap times as points
  theme_minimal() + # A clean, minimal theme for the plot
  labs(title = "Max Verstappen Lap Times in Jeddah - 2021 vs. 2022",
       x = "Lap Number",
       y = "Lap Time (Seconds)",
       color = "Season") +
  scale_color_manual(values = c("2021" = "blue", "2022" = "red"))


```

```{r}
#| echo: false
#| warning: false
#| message: false

library(ggplot2)
library(readr)
library(dplyr)

ham_jeddah_2022 <- read_csv("../data/analysis_data/hamilton_laps_jeddah_2022_cleaned.csv")
ham_jeddah_2021 <- read_csv("../data/analysis_data/hamilton_laps_jeddah_2021_cleaned.csv")

# Add a season column to each dataframe
ham_jeddah_2021$Season <- '2021'
ham_jeddah_2022$Season <- '2022'

# Combine the two dataframes
combined_df <- rbind(ham_jeddah_2021, ham_jeddah_2022)

# Create the plot
ggplot(combined_df, aes(x = `Lap #`, y = `LapTime in Seconds`, color = Season)) +
  geom_line() + # This will connect points with lines, showing the trend
  geom_point() + # This will plot individual lap times as points
  theme_minimal() + # A clean, minimal theme for the plot
  labs(title = "Lewis Hamilton Lap Times in Jeddah - 2021 vs. 2022",
       x = "Lap Number",
       y = "Lap Time (Seconds)",
       color = "Season") +
  scale_color_manual(values = c("2021" = "purple", "2022" = "yellow"))
```

# References


